name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the feature you'd like to see added.
      placeholder: "Add support for detecting Bazel project roots."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature important or useful?
      placeholder: "Makes `pk` more flexible across more build systems."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How should it work? Any design ideas or references?
      placeholder: "Add a Bazel detector in `build.rs` similar to Cargo or Gradle."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: If applicable, what else did you consider?
      placeholder: "Could be handled by plugin system, but better built-in."
